apiVersion: v2
name: helm-common
description: A collection of common Helm charts
type: library
version: 0.1.0
maintainers:
  - name: mano1233
    email: mano1233@example.com
keywords:
  - helm
  - charts
  - common
home: https://github.com/mano1233/helm-common
sources:
  - https://github.com/mano1233/helm-common 