{{- if .Values.ingress.enabled -}}
{{- $fullName := include "n8n.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.defaultBackend }}
  defaultBackend:
    {{- toYaml .Values.ingress.defaultBackend | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.rules }}
  rules:
    {{- toYaml .Values.ingress.rules | nindent 4 }}
  {{- end }}
{{- end }} 