apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-db
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.n8n.database.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-auth
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
stringData:
  basic-auth-password: {{ .Values.n8n.security.basicAuth.password | quote }}
  jwt-secret: {{ .Values.n8n.security.jwt.secret | quote }}
---
{{- if .Values.n8n.email.mode == "smtp" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-email
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
stringData:
  smtp-password: {{ .Values.n8n.email.smtp.pass | quote }}
{{- end }} 